root = "."
tmp_dir = "bin"

[build]
cmd = "go build -v -o ./bin/go-boilerplate ./internal/apps/rest"
bin = "bin/go-boilerplate"
full_bin = "APP_ENV=dev APP_USER=air ./bin/go-boilerplate"
include_ext = ["go", "tpl", "tmpl", "json", "sql", "yaml"]
exclude_dir = ["tmp", "vendor", "build"]
include_dir = []
exclude_file = []
log = "app.log"
delay = 1000 # ms
stop_on_error = true
send_interrupt = false
kill_delay = 500 # ms

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true